<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Марина Варфоломеева" />


<title>Методы выявления дифференциально-экспрессируемых белков</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; } /* Alert */
code span.an { color: #008000; } /* Annotation */
code span.at { } /* Attribute */
code span.bu { } /* BuiltIn */
code span.cf { color: #0000ff; } /* ControlFlow */
code span.ch { color: #008080; } /* Char */
code span.cn { } /* Constant */
code span.co { color: #008000; } /* Comment */
code span.cv { color: #008000; } /* CommentVar */
code span.do { color: #008000; } /* Documentation */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.im { } /* Import */
code span.in { color: #008000; } /* Information */
code span.kw { color: #0000ff; } /* Keyword */
code span.op { } /* Operator */
code span.ot { color: #ff4000; } /* Other */
code span.pp { color: #ff4000; } /* Preprocessor */
code span.sc { color: #008080; } /* SpecialChar */
code span.ss { color: #008080; } /* SpecialString */
code span.st { color: #008080; } /* String */
code span.va { } /* Variable */
code span.vs { color: #008080; } /* VerbatimString */
code span.wa { color: #008000; font-weight: bold; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' || rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="my_styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->



<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Proteomics course</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Начало</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Конспект
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="00_introduction.html">О модуле Анализ протеомных данных</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="01_introduction_to_r.html">Знакомство с R</a>
    </li>
    <li>
      <a href="02_data_preprocessing.html">Предварительная обработка данных</a>
    </li>
    <li>
      <a href="03_classification.html">Классификация</a>
    </li>
    <li class="dropdown-header">Дифференциальная экспрессия</li>
    <li class="divider"></li>
    <li>
      <a href="protocol.html">Протокол анализа данных</a>
    </li>
  </ul>
</li>
<li>
  <a href="resources.html">Ссылки и ресурсы</a>
</li>
<li>
  <a href="coding_practices.html">Правила хорошего кода</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Методы выявления дифференциально-экспрессируемых белков</h1>
<h4 class="author">Марина Варфоломеева</h4>

</div>


<hr />
<p>В этом разделе мы поговорим о том, как делать анализ дифференциальной экспрессии в R <span class="citation">(R Core Team 2018)</span>.</p>
<ul>
<li><p><a href="04_differential_expression_analysis.R">Код к этому занятию</a></p></li>
<li>Данные о протеоме жабр гребешка <em>Pecten maximus</em> из работы Artigaud et al. 2015
<ul>
<li><a href="data/Prot_Br_H_T.csv">Prot_Br_H_T.csv</a></li>
<li><a href="data/Prot_Br_H_T_factor.csv">Prot_Br_H_T_factor.csv</a></li>
</ul></li>
</ul>
<hr />
<div id="--" class="section level1">
<h1>Тестирование статистических гипотез</h1>
<p>Допустим, мы хотим сравнить уровень экспрессии белков у морских гребешков, которых содержали при разной температуре. Исходя из существующих исследований и общих знаний мы предполагаем, что уровень экспрессии некоторых белков будет различаться (это то, что мы на самом деле думаем — <strong>исследовательская гипотеза</strong>). Чтобы проверить исследовательскую гипотезу, нужна <strong>нулевая гипотеза</strong>. Обычно нулевые гипотезы постулируют отсутствие каких либо различий. Так и в этом примере, нулевая гипотеза говорит, что уровень экспрессии не будет различаться.</p>
<p>Далее, мы проводим эксперимент, измеряем уровень экспрессии. После этого рассчитываем статистику, которая позволит оценить разницу уровней экспрессии в эксперименте (например, t-критерий). Наблюдаемое в эксперименте значение статистики сравнивают со значением, которое было бы получено, если бы уровни экспрессии не различались (т.е. если нулевая гипотеза верна). Если это значение маловероятно получить, когда уровни экспрессии не различаются, то мы “отвергаем” нулевую гипотезу. В таком случае, мы считаем, что результаты нашего эксперимента говорят в пользу нашей исследовательской гипотезы.</p>
<p>При тестировании статистических гипотез возможно четыре варианта развития событий: мы можем принять верное решение (отвергнуть неправильную или принять верную <span class="math inline">\(H_0\)</span>), или мы можем ошибиться — тоже двумя разными способами. В таблице ниже показаны типы ошибок при проверке гипотез.</p>
<table>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"></th>
<th align="center"><span class="math inline">\(H_0\)</span> == TRUE</th>
<th align="center"><span class="math inline">\(H_0\)</span> == FALSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Отклоняем <span class="math inline">\(H_0\)</span></td>
<td align="center">Ошибка <strong>I</strong> рода </br>Ложно-положительный результат</td>
<td align="center">Правильно </br>Положительный результат</td>
</tr>
<tr class="even">
<td align="center">Сохраняем <span class="math inline">\(H_0\)</span></td>
<td align="center">Правильно </br>Отрицательный результат</td>
<td align="center">Ошибка <strong>II</strong> рода </br> Ложно-отрицательный результат</td>
</tr>
</tbody>
</table>
<p><img src="04_differential_expression_analysis_files/figure-html/power_beta-1.png" width="384" /></p>
<p><strong>Ошибки I рода</strong> возникают тогда, когда мы ошибочно отклоняем справедливую <span class="math inline">\(H_0\)</span>, т.е. находим различия там, где их нет на самом деле. Находить различия там, где их нет — значит множить сущности сверх необходимого. Поэтому вероятность ошибок I рода ученые договорились строго контролировать и следить, чтобы они появлялись не чаще, чем в 5% случаев. Иногда этот произвольно выбранный порог делают еще жестче — 1%. Вероятность ошибок I рода принято обозначать <span class="math inline">\(\alpha\)</span>. Это тот самый уровень значимости, с которым принято сравнивать доверительные вероятности (p-values), полученные в статистических тестах.</p>
<p><strong>Ошибки II рода</strong> возникают, когда мы ошибочно принимаем ложную <span class="math inline">\(H_0\)</span>, т.е. не находим различий, там, где они на самом деле есть. Несмотря на то, что про ошибки II рода реже вспоминают, их не менее обидно делать. Считается допустимым, если такие ошибки возникают не чаще чем в 20% случаев. Это тоже совершенно произвольно взятый порог. Вероятность ошибок II рода принято обозначать <span class="math inline">\(\beta\)</span>.</p>
<p><strong>Мощность теста</strong> — это способность выявлять различия, когда они есть на самом деле. Зная <span class="math inline">\(\beta\)</span> можно вычислить вероятность того, что статистический тест обнаружит различия <span class="math inline">\(Power = 1 - \beta\)</span></p>
<p><img src="04_differential_expression_analysis_files/figure-html/power-1.png" width="384" /></p>
<p>Мощность любого статистического теста будет больше:</p>
<ul>
<li>если величина эффекта (d, величина выявляемых различий) будет больше</li>
<li>если увеличить объем выборки</li>
<li>если повысить уровень значимости (например, вместо <span class="math inline">\(\alpha = 0.01\)</span>, взять <span class="math inline">\(\alpha = 0.05\)</span>)</li>
</ul>
<p>На примере t-критерия зависимость мощности от этих трех величин будет выглядеть так:</p>
<p><img src="04_differential_expression_analysis_files/figure-html/pwr_vs_n-1.png" width="672" /></p>
</div>
<div id="-----the-good-the-bad-and-the-ugly." class="section level1">
<h1>Способы выявления дифференциально экспрессируемых белков (The Good, The Bad, and The Ugly).</h1>
<p>Есть множество способов измерить разницу экспрессии. Вот самые распространенные:</p>
<ul>
<li><strong>fold change</strong> — соотношение уровеней экспрессии. Применяется, если нет повторностей. Грубый метод оценки, т.к. не позволяет оценить статистическую значимость.</li>
<li><strong>t-тест</strong> — при небольших выборках у него малая мощность из-за неточной оценки <span class="math inline">\(\sigma\)</span>.</li>
<li><strong>Модерированный t-тест</strong> (с использованием Empirical Bayes) — более мощный, чем обычный t-критерий. Позволяет точнее оценить <span class="math inline">\(\sigma\)</span> для конкретного белка, используя информацию о распределении <span class="math inline">\(\sigma\)</span> для всех белков.</li>
</ul>
</div>
<div id="fold-change-the-ugly" class="section level1">
<h1>Fold change (The Ugly)</h1>
<p><img src="images/the_ugly1.jpg" width=300px></p>
<p><strong>Fold change</strong> (FC) — исторически первый способ оценивать дифференциальную экспрессию. Его придумали в те времена, когда делать повторности было дорого. Договорились, что будем считать, что экспрессия меняется, если ее уровень сильно отличается между группами (в 1.5 или 2 раза).</p>
<p>Нужно оценить, во сколько раз экспрессия в одной группе больше, чем экспрессия в другой группе. FC — это пропорция, дробь, в числителе одна группа, в знаменателе другая.</p>
<p>Не надо усреднять соотношения!</p>
<p>Допустим, мы сравниваем уровень экспрессии до и после какого-то воздействия и у нас есть две повторности:</p>
<table>
<colgroup>
<col width="32%" />
<col width="25%" />
<col width="25%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"></th>
<th align="right">Повторность 1</th>
<th align="right">Повторность 2</th>
<th align="right">Среднее</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">До воздействия</td>
<td align="right"><span class="math inline">\(A_{1} = 1\)</span></td>
<td align="right"><span class="math inline">\(A_{2} = 10\)</span></td>
<td align="right"><span class="math inline">\(\bar{A} = 5.5\)</span></td>
</tr>
<tr class="even">
<td align="center">После воздействия</td>
<td align="right"><span class="math inline">\(B_{1} = 10\)</span></td>
<td align="right"><span class="math inline">\(B_{2} = 1\)</span></td>
<td align="right"><span class="math inline">\(\bar{B} = 5.5\)</span></td>
</tr>
<tr class="odd">
<td align="center"></td>
<td align="right"><span class="math inline">\(A_{1}/B_{1} = 1/10\)</span></td>
<td align="right"><span class="math inline">\(A_{2}/B_{2} = 10/1\)</span></td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="center">Соотношение экспрессии</td>
<td align="right"><span class="math display">\[\frac {A_{1}/B_{1}} {A_{2}/B_{2}} = \frac {1/10 + 10/1} {2} = 5.05\]</span> (<strong>Неправильно!</strong>)</td>
<td align="right"></td>
<td align="right"><span class="math display">\[\bar{A} / \bar{B} = 5.5/5.5 = 0\]</span> (<strong>Правильно!</strong>)</td>
</tr>
</tbody>
</table>
<p>В первой из повторностей уровень экспрессии cнизился в 10 раз (<span class="math inline">\(1/10\)</span>), а во второй — в 10 раз вырос (<span class="math inline">\(10/1\)</span>).</p>
<p>Если мы опрометчиво усредним эти соотношения <span class="math inline">\((1/10 + 10/1) / 2 = 5.05\)</span>, то получится, что уровень экспрессии в среднем вырос в 5 раз — ерунда.</p>
<p>Правильней было бы посчитать средний уровень экспрессии до (<span class="math inline">\((1 + 10)/2 = 5.5\)</span>) и после (<span class="math inline">\((10 + 1)/2 = 5.5\)</span>), и только потом посчитать их соотношение. Тогда мы получили бы гораздо более логичный результат: на самом деле соотношение уровней экспрессии не изменилось (<span class="math inline">\(5.5/5.5 = 1\)</span>).</p>
<p>Соотношения сырых данных экспрессии брать неудобно, потому что обычные соотношения распределены несимметрично вокруг 1. Сравните, например соотношения: <span class="math inline">\(1/5 = 0.2\)</span>, <span class="math inline">\(5/5 = 1\)</span> и <span class="math inline">\(5/1 = 5\)</span>.</p>
<p>Гораздо удобнее брать логарифм соотношения, потому что его величина распределена симметрично вокруг нуля (и тогда <span class="math inline">\(log(X) = -1 * log(1/X)\)</span>). Действительно, в нашем примере будет так: <span class="math inline">\(log(1/5) = -1.6\)</span>, <span class="math inline">\(log(5/5) = 0\)</span> и <span class="math inline">\(log(5/1) = 1.6\)</span>.</p>
<p>В симметричности распределения логарифмов соотношений мы можем убедиться при помощи простой симуляции.</p>
<p><img src="04_differential_expression_analysis_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>Операции с логарифмами:</p>
<ul>
<li><span class="math inline">\(log(1) = 0\)</span></li>
<li><span class="math inline">\(log(ab) = log(a) + log(b)\)</span></li>
<li><span class="math inline">\(log(a/b) = log(a) - log(b)\)</span> - это и есть fold change</li>
</ul>
<p>Обычно, данные логарифмируют при помощи логарифма по основанию 2 — <code>log2()</code>, чтобы облегчить сравнение fold change. Тогда, если экспрессия в 2 раза отличается между образцами, получится, что <span class="math inline">\(log2(2x/x) = log2(2) = 1\)</span>.</p>
<p>Основная проблема использования fold change — этот критерий выбирает гены, у которых самая большая разница экспрессии, но не позволяет проверить статистическую значимость различий. На самом деле, при наличии повторностей можно не использовать fold change, поскольку мы можем оценить статистическую значимость различий уровня экспрессии.</p>
</div>
<div id="t--the-bad" class="section level1">
<h1>t-тест (The Bad)</h1>
<p><img src="images/the_bad1.jpg" width=300px></p>
<p>Чтобы проверить гипотезу <span class="math inline">\(H_{0}: \bar{A} - \bar{B} = 0\)</span>, нужно оценить дисперсию в генеральной совокупности <span class="math inline">\(\sigma\)</span>. После этого можно воспользоваться t-критерий.</p>
<p><strong>t-критерий</strong></p>
<p><span class="math display">\[t = \frac {\bar {A} - \bar {B}} {SE_{A - B}}\]</span></p>
<p>Обычный t-тест исходит из предположения, что дисперсии в группах одинаковы. Обычно, это предположение нереалистично. Мы будем использовать модификацию t-теста для разных дисперсий в группах — т.наз. <strong>t-критерий Велша (Welch’s t-test)</strong>. Важно, что t-тестом Уэлча можно пользоваться, даже если дисперсии равны. Он немного консервативнее, чем тест Стьюдента.</p>
<p><span class="math display">\[t = \frac {\bar {A} - \bar {B}} {\sqrt{\frac{s^{2}_{a}}{n_a} + \frac{s^{2}_{b}}{n_b}}}\]</span> Приблизительное число степеней свободы для t распределения можно рассчитать по уравнению Уэлча-Саттеруэйта:</p>
<p><span class="math display">\[df_{ Welch-Satterthwaite} \approx \cfrac {\bigg(\cfrac{s^2_{x_1}}{n_{x_1}} + \cfrac{s^2_{x_2}}{n_{x_2}}\bigg)^2}
{\cfrac{1}{n_{x_1} - 1}\bigg(\cfrac {s_{x_1}^2} {n_{x_1}}\bigg)^2 + \cfrac{1}{n_{x_2} - 1}\bigg(\cfrac {s_{x_2}^2} {n_{x_2}}\bigg)^2}\]</span></p>
<p>Условия применимости:</p>
<ul>
<li>Наблюдения должны быть независимы друг от друга.</li>
<li>Выборки должны быть независимы (либо должна использоваться специальная модификация теста для зависимых выборок).</li>
<li>Если большой объем выборки (N &gt; 30), то распределение t-статистики приближается к нормальному. К сожалению, в протеомике как правило используются небольшие выборки.</li>
<li>Если данные распределены нормально, то при любом объеме выборки t-статистика подчиняется t-распределению с числом степеней свободы <em>df</em>. К счастью, в логарифмической шкале значения экспрессии распределены нормально.</li>
</ul>
<p>Далее при t-тесте следуют действия, обычные при тестировании гипотез:</p>
<ul>
<li>Считаем t-статистику.</li>
<li>Считаем вероятность получить такое значение статистики при условии, что нулевая гипотеза верна (p-value).</li>
<li>Сравниваем эту вероятность (p-value) с заданным уровнем значимости (<span class="math inline">\(\alpha\)</span>). Если эта вероятность меньше заданного уровня значимости — отвергаем нулевую гипотезу.</li>
</ul>
<p><strong>Осторожнее с выводами! Значение p ничего не говорит о том, верна ли на самом деле нулевая гипотеза.</strong></p>
<div id="----pecten-maximus" class="section level2">
<h2>Экспрессия белков у гребешков <em>Pecten maximus</em></h2>
<p>Как работае t-тест мы будем разбирать на примере более полных данных об экспрессии белков у гребешков из работы <span class="citation">(<span class="citeproc-not-found" data-reference-id="artigaud2015proteomic"><strong>???</strong></span>)</span>.</p>
<div id="-1" class="section level3">
<h3>Задание 1</h3>
<ul>
<li>Откройте данные из файлов <code>Prot_Br_H_T.csv</code> и <code>Prot_Br_H_T_factor.csv</code> и сохраните их в переменных <code>expr</code> и <code>fact</code>.</li>
<li>Трансформируйте и нормализуйте значения экспрессии.</li>
<li>Посмотрите, какая информация известна о пробах.</li>
</ul>
<button class="btn btn-primary btn-sm" data-toggle="collapse" data-target="#hide_buttonunnamed-chunk-2">
Решение
</button>
<div id="hide_buttonunnamed-chunk-2" class="collapse">
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">library</span>(limma)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="co"># Открываем данные экспрессии</span></a>
<a class="sourceLine" id="cb1-3" data-line-number="3">expr &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;data/Prot_Br_H_T.csv&quot;</span>, <span class="dt">header =</span> <span class="ot">TRUE</span>, <span class="dt">sep =</span> <span class="st">&quot;;&quot;</span>, <span class="dt">row.names =</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb1-4" data-line-number="4">fact &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;data/Prot_Br_H_T_factor.csv&quot;</span>, <span class="dt">header =</span> <span class="ot">TRUE</span>, <span class="dt">sep =</span> <span class="st">&quot;;&quot;</span>, <span class="dt">row.names =</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb1-5" data-line-number="5"></a>
<a class="sourceLine" id="cb1-6" data-line-number="6"><span class="co"># Хорошо бы проверить, соответствует ли число проб в обоих файлах</span></a>
<a class="sourceLine" id="cb1-7" data-line-number="7"><span class="kw">dim</span>(expr)</a></code></pre></div>
<pre class="r-output"><code>## [1] 647  30
</code></pre>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1"><span class="kw">dim</span>(fact)</a></code></pre></div>
<pre class="r-output"><code>## [1] 30  2
</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="co"># Есть ли пропущенные значения?</span></a>
<a class="sourceLine" id="cb3-2" data-line-number="2"><span class="kw">colSums</span>(<span class="kw">is.na</span>(expr))</a></code></pre></div>
<pre class="r-output"><code>## HT_Br_141_27754 HT_Br_142_27755 HT_Br_143_27756 HT_Br_145_27757 
##               0               0               0               0 
## HT_Br_153_27758 HT_Br_182_30362 HT_Br_184_30363 HT_Br_186_30343 
##               0               0               0               0 
## HT_Br_185_30364 HT_Br_189_30367 HT_Br_221_30350 HT_Br_222_30351 
##               0               0               0               0 
## HT_Br_227_30353 HT_Br_229_30354 HT_Br_233_30355 HT_Br_122_27749 
##               0               0               0               0 
## HT_Br_123_27750 HT_Br_125_27751 HT_Br_126_27752 HT_Br_129_27753 
##               0               0               0               0 
## HT_Br_161_27759 HT_Br_162_27760 HT_Br_166_30359 HT_Br_172_30342 
##               0               0               0               0 
## HT_Br_173_30361 HT_Br_202_30368 HT_Br_203_30369 HT_Br_204_30346 
##               0               0               0               0 
## HT_Br_205_30347 HT_Br_207_30345 
##               0               0
</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1"><span class="co"># Есть ли нули (они будут мешать при логарифмировании)</span></a>
<a class="sourceLine" id="cb4-2" data-line-number="2"><span class="kw">colSums</span>(expr <span class="op">==</span><span class="st"> </span><span class="dv">0</span>)</a></code></pre></div>
<pre class="r-output"><code>## HT_Br_141_27754 HT_Br_142_27755 HT_Br_143_27756 HT_Br_145_27757 
##               0               0               0               0 
## HT_Br_153_27758 HT_Br_182_30362 HT_Br_184_30363 HT_Br_186_30343 
##               0               0               1              12 
## HT_Br_185_30364 HT_Br_189_30367 HT_Br_221_30350 HT_Br_222_30351 
##               5               7               6               5 
## HT_Br_227_30353 HT_Br_229_30354 HT_Br_233_30355 HT_Br_122_27749 
##              16               0              43               0 
## HT_Br_123_27750 HT_Br_125_27751 HT_Br_126_27752 HT_Br_129_27753 
##               0               0               0               0 
## HT_Br_161_27759 HT_Br_162_27760 HT_Br_166_30359 HT_Br_172_30342 
##               0               0               0              12 
## HT_Br_173_30361 HT_Br_202_30368 HT_Br_203_30369 HT_Br_204_30346 
##              13              24              11               7 
## HT_Br_205_30347 HT_Br_207_30345 
##              20             132
</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1"><span class="co"># нормализуем и логарифмируем</span></a>
<a class="sourceLine" id="cb5-2" data-line-number="2">expr_norm &lt;-<span class="st"> </span><span class="kw">normalizeQuantiles</span>(<span class="kw">log2</span>(expr <span class="op">+</span><span class="st"> </span><span class="dv">1</span>))</a>
<a class="sourceLine" id="cb5-3" data-line-number="3"></a>
<a class="sourceLine" id="cb5-4" data-line-number="4"><span class="co"># Что известно о пробах?</span></a>
<a class="sourceLine" id="cb5-5" data-line-number="5"><span class="kw">str</span>(fact)</a></code></pre></div>
<pre class="r-output"><code>## 'data.frame':    30 obs. of  2 variables:
##  $ Oxygen     : Factor w/ 2 levels "Hypox","Normox": 2 2 2 2 2 2 2 2 2 2 ...
##  $ Temperature: Factor w/ 3 levels "10C","18C","25C": 1 1 1 1 1 2 2 2 2 2 ...
</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1"><span class="kw">table</span>(fact<span class="op">$</span>Oxygen, fact<span class="op">$</span>Temperature)</a></code></pre></div>
<pre class="r-output"><code>##         
##          10C 18C 25C
##   Hypox    5   5   5
##   Normox   5   5   5
</code></pre>
</div>
<p><br /></p>
</div>
<div id="-2" class="section level3">
<h3>Задание 2</h3>
<p>Отберите только данные экспрессии и метаданные, относящиеся к гребешкам из 10 и 25 градусов, которые жили при нормальном количестве кислорода. Назовите получившиеся переменные <code>expr_subset</code> и <code>fact_subset</code>.</p>
<button class="btn btn-primary btn-sm" data-toggle="collapse" data-target="#hide_buttonunnamed-chunk-3">
Решение
</button>
<div id="hide_buttonunnamed-chunk-3" class="collapse">
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1">f_subset &lt;-<span class="st"> </span>fact<span class="op">$</span>Oxygen <span class="op">==</span><span class="st"> &quot;Normox&quot;</span> <span class="op">&amp;</span><span class="st"> </span>fact<span class="op">$</span>Temperature <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;10C&quot;</span>, <span class="st">&quot;25C&quot;</span>)</a>
<a class="sourceLine" id="cb7-2" data-line-number="2">expr_subset &lt;-<span class="st"> </span>expr_norm[, f_subset]</a>
<a class="sourceLine" id="cb7-3" data-line-number="3">fact_subset &lt;-<span class="st"> </span><span class="kw">droplevels</span>(fact[f_subset, ])</a></code></pre></div>
</div>
<p><br /></p>
</div>
</div>
<div id="t---r" class="section level2">
<h2>t-тест в R</h2>
<p>Давайте сравним уровень экспрессии одного из белков (например, шестого) между группами при помощи простого t-критерия.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1">groups &lt;-<span class="st"> </span>fact_subset<span class="op">$</span>Temperature <span class="op">==</span><span class="st"> &quot;10C&quot;</span></a>
<a class="sourceLine" id="cb8-2" data-line-number="2"><span class="kw">t.test</span>(<span class="dt">x =</span> expr_subset[<span class="dv">6</span>, groups], <span class="dt">y =</span> expr_subset[<span class="dv">6</span>, <span class="op">!</span>groups])</a></code></pre></div>
<pre class="r-output"><code>## 
##  Welch Two Sample t-test
## 
## data:  expr_subset[6, groups] and expr_subset[6, !groups]
## t = 6.3396, df = 4.6953, p-value = 0.001812
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  3.393881 8.180017
## sample estimates:
## mean of x mean of y 
##  19.53025  13.74330
</code></pre>
<p>Но у нас всего 647 белков. Было бы не удобно делать все эти сравнения вручную. Поэтому, давайте научимся добывать из объекта, возвращаемого <code>t.test()</code> значение p-value.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1">t_result &lt;-<span class="st"> </span><span class="kw">t.test</span>(<span class="dt">x =</span> expr_subset[<span class="dv">6</span>, groups], <span class="dt">y =</span> expr_subset[<span class="dv">6</span>, <span class="op">!</span>groups])</a>
<a class="sourceLine" id="cb9-2" data-line-number="2"><span class="kw">str</span>(t_result)</a></code></pre></div>
<pre class="r-output"><code>## List of 9
##  $ statistic  : Named num 6.34
##   ..- attr(*, "names")= chr "t"
##  $ parameter  : Named num 4.7
##   ..- attr(*, "names")= chr "df"
##  $ p.value    : num 0.00181
##  $ conf.int   : num [1:2] 3.39 8.18
##   ..- attr(*, "conf.level")= num 0.95
##  $ estimate   : Named num [1:2] 19.5 13.7
##   ..- attr(*, "names")= chr [1:2] "mean of x" "mean of y"
##  $ null.value : Named num 0
##   ..- attr(*, "names")= chr "difference in means"
##  $ alternative: chr "two.sided"
##  $ method     : chr "Welch Two Sample t-test"
##  $ data.name  : chr "expr_subset[6, groups] and expr_subset[6, !groups]"
##  - attr(*, "class")= chr "htest"
</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1">t_result<span class="op">$</span>p.value</a></code></pre></div>
<pre class="r-output"><code>## [1] 0.001811669
</code></pre>
<p>Теперь мы готовы посчитать t-тест для каждого белка. Для этого нам понадобится:</p>
<ol style="list-style-type: decimal">
<li>написать функцию, которая считает t-test и добывает p-value</li>
<li>к каждой строке данных применить наш t.test</li>
</ol>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1"><span class="co"># 1) пишем функцию, которая считает t-test и добывает p-value</span></a>
<a class="sourceLine" id="cb11-2" data-line-number="2">t_p_val &lt;-<span class="st"> </span><span class="cf">function</span>(x, f1, f2) {</a>
<a class="sourceLine" id="cb11-3" data-line-number="3">  <span class="kw">tryCatch</span>(<span class="kw">t.test</span>(<span class="dt">x =</span> x[f1], <span class="dt">y =</span> x[f2])<span class="op">$</span>p.value,</a>
<a class="sourceLine" id="cb11-4" data-line-number="4">           <span class="dt">error =</span> <span class="cf">function</span>(e) <span class="ot">NA</span>)</a>
<a class="sourceLine" id="cb11-5" data-line-number="5">}</a>
<a class="sourceLine" id="cb11-6" data-line-number="6"><span class="co"># тестируем функцию</span></a>
<a class="sourceLine" id="cb11-7" data-line-number="7"><span class="kw">t_p_val</span>(expr_subset[<span class="dv">6</span>, ], <span class="dt">f1 =</span> groups, <span class="dt">f2 =</span> <span class="op">!</span>groups)</a></code></pre></div>
<pre class="r-output"><code>## [1] 0.001811669
</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1"><span class="co"># 2) к каждой строке данных применяем наш t.test</span></a>
<a class="sourceLine" id="cb12-2" data-line-number="2">pvals &lt;-<span class="st"> </span><span class="kw">apply</span>(<span class="dt">X =</span> expr_subset, <span class="dt">MARGIN =</span> <span class="dv">1</span>, <span class="dt">FUN =</span> t_p_val, </a>
<a class="sourceLine" id="cb12-3" data-line-number="3">               <span class="dt">f1 =</span> groups, <span class="dt">f2 =</span> <span class="op">!</span>groups)</a></code></pre></div>
<p>Все готово, мы посчитали p-values для всех белков.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="co"># В результате мы получаем вектор p-values</span></a>
<a class="sourceLine" id="cb13-2" data-line-number="2"><span class="kw">head</span>(pvals)</a></code></pre></div>
<pre class="r-output"><code>##          45          53          27          54          66          75 
## 0.293428958 0.667581658 0.209929631 0.003545320 0.278472659 0.001811669
</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1"><span class="kw">class</span>(pvals)</a></code></pre></div>
<pre class="r-output"><code>## [1] "numeric"
</code></pre>
<div id="-3" class="section level3">
<h3>Задание 3</h3>
<ul>
<li>Сколько белков, значимо меняющих экспрессию, мы нашли?</li>
<li>Экспрессия каких белков различается?</li>
</ul>
<button class="btn btn-primary btn-sm" data-toggle="collapse" data-target="#hide_buttonunnamed-chunk-8">
Решение
</button>
<div id="hide_buttonunnamed-chunk-8" class="collapse">
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1"><span class="co"># Сколько белков, значимо меняющих экспрессию, мы нашли?</span></a>
<a class="sourceLine" id="cb15-2" data-line-number="2"><span class="kw">sum</span>(pvals <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre class="r-output"><code>## [1] 254
</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1"><span class="co"># Экспрессия каких белков различается?</span></a>
<a class="sourceLine" id="cb16-2" data-line-number="2">ids_dif &lt;-<span class="st"> </span><span class="kw">which</span>(pvals <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>)</a>
<a class="sourceLine" id="cb16-3" data-line-number="3"><span class="kw">rownames</span>(expr_subset)[ids_dif]</a></code></pre></div>
<pre class="r-output"><code>##   [1] "54"   "75"   "68"   "102"  "149"  "150"  "160"  "151"  "164"  "165" 
##  [11] "179"  "211"  "261"  "278"  "268"  "272"  "266"  "292"  "275"  "271" 
##  [21] "263"  "276"  "280"  "290"  "294"  "320"  "321"  "363"  "373"  "361" 
##  [31] "439"  "421"  "434"  "424"  "427"  "448"  "450"  "431"  "440"  "486" 
##  [41] "510"  "519"  "512"  "514"  "611"  "503"  "505"  "533"  "535"  "555" 
##  [51] "530"  "529"  "574"  "523"  "542"  "571"  "575"  "540"  "541"  "543" 
##  [61] "532"  "547"  "562"  "561"  "583"  "602"  "604"  "624"  "625"  "621" 
##  [71] "637"  "623"  "629"  "633"  "627"  "631"  "643"  "642"  "646"  "668" 
##  [81] "659"  "663"  "672"  "706"  "678"  "681"  "697"  "693"  "694"  "709" 
##  [91] "728"  "710"  "707"  "708"  "713"  "691"  "704"  "729"  "740"  "747" 
## [101] "733"  "730"  "731"  "742"  "732"  "739"  "736"  "745"  "744"  "748" 
## [111] "755"  "756"  "757"  "760"  "774"  "771"  "763"  "820"  "781"  "799" 
## [121] "801"  "809"  "802"  "827"  "811"  "817"  "814"  "800"  "834"  "832" 
## [131] "837"  "831"  "840"  "845"  "856"  "855"  "876"  "877"  "879"  "882" 
## [141] "898"  "902"  "916"  "913"  "914"  "904"  "918"  "945"  "938"  "954" 
## [151] "948"  "959"  "957"  "985"  "975"  "986"  "1004" "1005" "994"  "1003"
## [161] "1021" "1024" "1036" "1063" "1055" "1074" "1057" "1048" "1062" "1058"
## [171] "1081" "1090" "1100" "1113" "1106" "1117" "1121" "1143" "1134" "1159"
## [181] "1171" "1170" "1197" "1216" "1232" "1228" "1282" "1287" "1301" "1309"
## [191] "1298" "1340" "1362" "1361" "1341" "1343" "1351" "1420" "1425" "1438"
## [201] "1430" "1452" "1500" "1483" "1519" "1491" "1478" "1493" "1578" "1601"
## [211] "1575" "1627" "1612" "1631" "1638" "1651" "1685" "1710" "1688" "1690"
## [221] "1708" "1700" "1699" "1801" "1804" "1749" "1782" "1842" "1822" "1838"
## [231] "1812" "1897" "1862" "1893" "1908" "1887" "1889" "1914" "1900" "1950"
## [241] "1924" "2004" "2034" "2112" "2110" "2165" "2283" "2203" "2312" "2257"
## [251] "2385" "2391" "2813" "2815"
</code></pre>
</div>
<p><br /></p>
<p><strong>Но это пока еще не правильные p-values!</strong></p>
</div>
</div>
</div>
<div id="--" class="section level1">
<h1>Проблема множественных тестов</h1>
<p>В результате протеомного исследования обычно получают данные об экспрессии сотен–тысяч белков. При анализе дифференциальной экспрессии для каждого белка нам нужно протестировать нулевую гипотезу <span class="math inline">\(H_0: \bar{A} = \bar{B}\)</span>.</p>
<p>В случае, если у нас всего один белок — мы делаем всего один статистический тест. В этом единственном тесте мы заранее фиксируем вероятность совершить ошибку I рода на уровне значимости <span class="math inline">\(\alpha = 0.05\)</span> (или <span class="math inline">\(\alpha = 0.01\)</span>).</p>
<p>Но представьте себе, что мы сравниваем уровень экспрессии 1000 белков. Даже если на самом деле их экспрессия не различается в двух группах (<span class="math inline">\(H_0\)</span> на самом деле справедлива), мы получим по крайней мере в 50 из этих тестов <span class="math inline">\(p &lt; 0.05\)</span>. Т.е. в 50 из 1000 тестов мы совершим ошибку I рода — найдем различия экспрессии там, где их нет. Это непозволительно большое количество ошибок.</p>
<p>Если вероятность ошибки I рода <span class="math inline">\(\alpha = 0.05\)</span>, тогда</p>
<p>Вероятность не совершить ошибку первого рода <span class="math inline">\(1 - \alpha\)</span>.</p>
<p>Вероятность не совершить ошибку первого рода ни в одном из сравнений <span class="math inline">\((1 - \alpha)^{m}\)</span></p>
<p>Вероятность совершить хотябы одну ошибку первого рода в группе сравнений <span class="math inline">\(1 - (1 - \alpha)^{m}\)</span></p>
<table>
<colgroup>
<col width="19%" />
<col width="25%" />
<col width="55%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Если не делать поправок на число сравнений…</th>
<th align="center">1 сравнение</th>
<th align="center">семейство из 1000 сравнений</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Число ошибок I рода на число сравнений<br />Per comparison error rate</td>
<td align="center">0.05</td>
<td align="center">0.05</td>
</tr>
<tr class="even">
<td align="center">Ожидаемое число ошибок <br /> Per family error rate</td>
<td align="center">0.05</td>
<td align="center">0.05 * 1000 = 50</td>
</tr>
<tr class="odd">
<td align="center">Вероятность получить хотябы одну ошибку I рода <br /> Family-wise error rate (FWER)</td>
<td align="center">0.05</td>
<td align="center"><span class="math display">\[1 - (1 - 0.05)^{1000} = 1\]</span></td>
</tr>
</tbody>
</table>
<div id="------i--family-wise-error-rate-fwer" class="section level2">
<h2>Контроль вероятности совершить хоть одну ошибку I рода (Family-wise error rate, FWER)</h2>
<p><strong>Вероятность получить хотябы одну ошибку I рода в группе сравнений (Family-wise error rate, FWER)</strong> можно зафиксировать на каком-нибудь приемлемом уровне. Примеры таких процедур — поправка Бонферрони и метод Хольма-Бонферрони.</p>
<p><strong>Поправка Бонферрони</strong> — процедура в один шаг. Отклоняем все нулевые гипотезы, для которых <span class="math inline">\(p \le \frac {\alpha} {m}\)</span>. Например, если вам нужно сделать 1000 сравнений, чтобы вероятность совершить ошибку I рода была 0.05, то нужно использовать <span class="math inline">\(p = 0.05/1000 = 0.00005\)</span> для каждого сравнения. Это очень жесткая поправка. Мощность такого теста будет очень мала.</p>
<p><strong>Метод Хольма-Бонферрони</strong> — пошаговая процедура.</p>
<p>Чтобы зафиксировать <span class="math inline">\(FWER \le \alpha\)</span>:</p>
<ul>
<li>Сортируем {p_n} p-values, полученные в тестах, в порядке возрастания</li>
</ul>
<p><span class="math inline">\(p_{1} \le p_{2} \le \cdots \le p_{n - 1} \le p_{n}\)</span></p>
<ul>
<li>Вводим поправку для уровня значимости</li>
</ul>
<p><span class="math inline">\(\hat{p_{j}} = min{\{(n - j + 1) \cdot p_{j}, 1\}}\)</span></p>
<p>В таблице приведены результаты нескольких сравнений. Для каждой из доверительных вероятностей (p-values) мы получили свой порог значимости при помощи поправки Хольма-Бонферрони:</p>
<table>
<thead>
<tr class="header">
<th align="right">Ранг (<span class="math inline">\(j\)</span>)</th>
<th align="right"><span class="math inline">\(\mathbf{p_{j}}\)</span></th>
<th align="right"><span class="math inline">\((n - j + 1)\)</span></th>
<th align="right"><span class="math inline">\(\mathbf{\hat{p_{j}}}\)</span></th>
<th align="left">Отвергаем <span class="math inline">\(H_0\)</span>?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">5</td>
<td align="right">0.015</td>
<td align="right">1</td>
<td align="right">0.015</td>
<td align="left">Да</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">0.010</td>
<td align="right">2</td>
<td align="right">0.020</td>
<td align="left">Да</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">0.035</td>
<td align="right">3</td>
<td align="right">0.105</td>
<td align="left">Нет</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">0.040</td>
<td align="right">4</td>
<td align="right">0.160</td>
<td align="left">Нет</td>
</tr>
<tr class="odd">
<td align="right">1</td>
<td align="right">0.046</td>
<td align="right">5</td>
<td align="right">0.230</td>
<td align="left">Нет</td>
</tr>
</tbody>
</table>
<p>Недостаток применения контроля FWER — снижение мощности всех тестов: мы каким либо способом снижаем <span class="math inline">\(\alpha\)</span> для каждого сравнения, в результате возрастает <span class="math inline">\(\beta\)</span>, а значит снижается мощность <span class="math inline">\(1 - \beta\)</span>.</p>
<p>Процедуры контроля FWER неоправданно жесткие. Они контролируют вероятность возникновения <strong>хотябы одной</strong> ошибки первого рода в группе сравнений. Эти процедуры устроены так, как будто мы проверяем обобщенную нулевую гипотезу — об отсутствии различий во всех сравнениях. На самом деле, эта гипотеза редко интересна с практической точки зрения. Считается, что небольшое число ошибок I рода все же можно допустить (например, при анализе геномных или протеомных данных). Именно поэтому часто указывают не уровни значимости после коррекции на множественные сравнения (p-values), а частоту ложноположительных результатов (частоту возникновения ошибок I рода).</p>
</div>
<div id="----false-discovery-rate-fdr" class="section level2">
<h2>Контроль частоты ложноположительных результатов (false discovery rate, FDR)</h2>
<p><strong>Частота ложноположительных результатов (false discovery rate, FDR)</strong> — это доля ошибок I рода относительно общего числа отвегнутых <span class="math inline">\(H_0\)</span>. Для контроля FDR используется, например, процедура Беньямини-Хохберга.</p>
<p>Алгоритм процедуры Беньямини-Хохберга</p>
<p>Чтобы зафиксировать <span class="math inline">\(FDR \le \gamma\)</span>:</p>
<ul>
<li>Сортируем {p_n} p-values, полученные в тестах, в порядке возрастания</li>
</ul>
<p><span class="math inline">\(p_{1} \le p_{2} \le \cdots \le p_{n - 1} \le p_{n}\)</span></p>
<ul>
<li>Находим такое значение p-value с наибольшим рангом <span class="math inline">\(j\)</span>, чтобы</li>
</ul>
<p><span class="math inline">\(p_{j} \le \frac{j}{n}\times \gamma\)</span></p>
<ul>
<li>Различия во всех тестах с рангами меньше <span class="math inline">\(j\)</span> считаем значимыми</li>
</ul>
<p>Для каждого теста можно вычислить точную ожидаемую долю ложноположительных результатов. <span class="math inline">\(\mathbf{q-value}\)</span> — минимальное значение FDR при котором результат конкретного теста можно считать значимым (Storey 2002, Storey Tibshirani 2003).</p>
<p>Например, для 15 сравнений результаты процедуры Беньямини-Хохберга могут выглядеть так:</p>
<table>
<colgroup>
<col width="12%" />
<col width="19%" />
<col width="40%" />
<col width="19%" />
<col width="8%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">Ранг (<span class="math inline">\(j\)</span>)</th>
<th align="right"><span class="math inline">\(\mathbf{p_{j}}\)</span></th>
<th align="right"><span class="math inline">\(\mathbf{\frac{j}{n}\times \gamma}\)</span></th>
<th align="left">Отвергаем <span class="math inline">\(H_0\)</span>?</th>
<th align="right">q-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">0.0001</td>
<td align="right">0.0033333</td>
<td align="left">Да</td>
<td align="right">0.0015</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">0.0003</td>
<td align="right">0.0066667</td>
<td align="left">Да</td>
<td align="right">0.0022</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">0.0053</td>
<td align="right">0.0100000</td>
<td align="left">Да</td>
<td align="right">0.0189</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">0.0057</td>
<td align="right">0.0133333</td>
<td align="left">Да</td>
<td align="right">0.0189</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">0.0063</td>
<td align="right">0.0166667</td>
<td align="left">Да</td>
<td align="right">0.0189</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">0.0083</td>
<td align="right">0.0200000</td>
<td align="left">Да</td>
<td align="right">0.0199</td>
</tr>
<tr class="odd">
<td align="right">7</td>
<td align="right">0.0093</td>
<td align="right">0.0233333</td>
<td align="left">Да</td>
<td align="right">0.0199</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="right">0.0195</td>
<td align="right">0.0266667</td>
<td align="left">Да</td>
<td align="right">0.0366</td>
</tr>
<tr class="odd">
<td align="right">9</td>
<td align="right">0.0332</td>
<td align="right">0.0300000</td>
<td align="left">Нет</td>
<td align="right">0.0553</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">0.0489</td>
<td align="right">0.0333333</td>
<td align="left">Нет</td>
<td align="right">0.0682</td>
</tr>
<tr class="odd">
<td align="right">11</td>
<td align="right">0.0500</td>
<td align="right">0.0366667</td>
<td align="left">Нет</td>
<td align="right">0.0682</td>
</tr>
<tr class="even">
<td align="right">12</td>
<td align="right">0.0560</td>
<td align="right">0.0400000</td>
<td align="left">Нет</td>
<td align="right">0.0700</td>
</tr>
<tr class="odd">
<td align="right">13</td>
<td align="right">0.0622</td>
<td align="right">0.0433333</td>
<td align="left">Нет</td>
<td align="right">0.0718</td>
</tr>
<tr class="even">
<td align="right">14</td>
<td align="right">0.0798</td>
<td align="right">0.0466667</td>
<td align="left">Нет</td>
<td align="right">0.0805</td>
</tr>
<tr class="odd">
<td align="right">15</td>
<td align="right">0.0805</td>
<td align="right">0.0500000</td>
<td align="left">Нет</td>
<td align="right">0.0805</td>
</tr>
</tbody>
</table>
</div>
<div id="-fwer--fdr--r" class="section level2">
<h2>Контроль FWER и FDR в R</h2>
<p>Поправки к p-values в R можно сделать при помощи функции <code>p.adjust()</code>. Аргумент <code>method</code> функции <code>p.adjust()</code> задает тип поправки.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1">p_bonf &lt;-<span class="st"> </span><span class="kw">p.adjust</span>(pvals, <span class="dt">method =</span> <span class="st">&quot;bonferroni&quot;</span>)</a>
<a class="sourceLine" id="cb17-2" data-line-number="2"><span class="co"># было</span></a>
<a class="sourceLine" id="cb17-3" data-line-number="3"><span class="kw">head</span>(pvals)</a></code></pre></div>
<pre class="r-output"><code>##          45          53          27          54          66          75 
## 0.293428958 0.667581658 0.209929631 0.003545320 0.278472659 0.001811669
</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1"><span class="co"># стало</span></a>
<a class="sourceLine" id="cb18-2" data-line-number="2"><span class="kw">head</span>(p_bonf)</a></code></pre></div>
<pre class="r-output"><code>## 45 53 27 54 66 75 
##  1  1  1  1  1  1
</code></pre>
<p>У скольких белков экспрессия значимо различается после поправки Бонферрони?</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1"><span class="kw">sum</span>(p_bonf <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre class="r-output"><code>## [1] 1
</code></pre>
<p>Названия белков, экспрессия которых значимо различается после поправки Бонферрони?</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1"><span class="kw">names</span>(pvals)[p_bonf <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>]</a></code></pre></div>
<pre class="r-output"><code>## [1] "583" NA    NA
</code></pre>
<div id="-4" class="section level3">
<h3>Задание 4</h3>
<ul>
<li>Cколько значимо различающихся белков будет найдено после поправки Хольма?</li>
<li>Cколько — после применения процедуры Беньямини-Хохберга?</li>
</ul>
<button class="btn btn-primary btn-sm" data-toggle="collapse" data-target="#hide_buttonunnamed-chunk-14">
Решение
</button>
<div id="hide_buttonunnamed-chunk-14" class="collapse">
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1"><span class="co"># С поправкой Хольма</span></a>
<a class="sourceLine" id="cb21-2" data-line-number="2">p_holm &lt;-<span class="st"> </span><span class="kw">p.adjust</span>(pvals, <span class="dt">method =</span> <span class="st">&quot;holm&quot;</span>)</a>
<a class="sourceLine" id="cb21-3" data-line-number="3"><span class="kw">sum</span>(p_holm <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre class="r-output"><code>## [1] 1
</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1"><span class="co"># После процедуры Беньямини-Хохберга (FDR)</span></a>
<a class="sourceLine" id="cb22-2" data-line-number="2">p_bh &lt;-<span class="st"> </span><span class="kw">p.adjust</span>(pvals, <span class="dt">method =</span> <span class="st">&quot;BH&quot;</span>)</a>
<a class="sourceLine" id="cb22-3" data-line-number="3"><span class="kw">sum</span>(p_bh <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.05</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre class="r-output"><code>## [1] 113
</code></pre>
</div>
<p><br /></p>
</div>
</div>
</div>
<div id="---t-" class="section level1">
<h1>Проблемы с обычным t-тестом</h1>
<div id="t-----t-" class="section level2">
<h2>1.t-статистика может не следовать t-распределению</h2>
<p>t-статистика, вычисленная на реальных данных может быть не t-распределена, из-за этого можно прийти к неправильным выводам.</p>
<p>Возможные решения:</p>
<ul>
<li>использование непараметрических тестов, которые не делают никаких предположений о форме распределения. Недостаток — малая мощность.</li>
<li>использование бутстреп-оценок. Недостаток — нужен большой объем выборок.</li>
</ul>
</div>
<div id="------" class="section level2">
<h2>2.Дисперсия экспрессии оценивается неточно на малых выборках</h2>
<p>При рассчете обычного t-критерия для оценки дисперсии экспрессии белков используется выборочная оценка дисперсии. Если повторностей мало, то оценки дисперсии получаются нестабильными и не точными. t-критерий лучше работает при <strong>большом</strong> числе повторностей, т.к. тогда при помощи <span class="math inline">\(s^2\)</span> удается точнее оценить <span class="math inline">\(\sigma^2\)</span>.</p>
<p>Есть другие способы оценить дисперсию — можно использовать информацию о других белках, чтобы оценить распределение возможных значений дисперсии (модерируемый t-критерий, см. ниже).</p>
</div>
<div id="--" class="section level2">
<h2>3.Разная дисперсия экспрессии</h2>
<p>У разных белков может быть очень разная дисперсия экспрессии.</p>
<!-- График: несколько белков, по оси х группы, по оси н уровень экспрессии. То же самое можно в виде боксплота, если много значений (больше 5). Каким различиям средних мы будем больше верить --- там где большая или маленькая дисперсия? -->
<!-- ```{r variability} -->
<!-- ``` -->
<p>Часто оказывается, что большая разница уровней экспрессии наблюдается у белков с низким уровнем экспрессии.</p>
<!-- RI-plot - график, где по одной оси (I) --- интенсивность экспрессии, а по другой оси (R) --- логарифм соотношения уровней экспрессии.  -->
<!-- ```{r riplot} -->
<!-- ``` -->
<p>Из-за этой особенности данных простое применение t-критерия может привести к некорректным выводам:</p>
<ul>
<li>Даже ничтожные различия уровня экспрессии могут оказаться достоверными для белков с небольшой дисперсией экспрессии (т.к. небольшие стандартные ошибки).</li>
<li>Даже очень сильные различия уровня экспрессии могут оказаться недостоверными для белков с большой дисперсией экспрессии (т.к. стандартные ошибки велики).</li>
</ul>
<!-- volcano plot: по оси х разница средних логарифмов экспрессии, по оси y - $-log_{10}p-value$. Граница уровня значимости на лог шкале $-log_{10}0.01 = 2$, все что выше - значимо, все что ниже - нет. Сверху, справа и слева - белки, которы значимо меняют экспрессию в ту и др. сторону больше чем в заданное число раз. Внизу справа и слева - белки, которые сильно но незначимо меняют экспрессию. -->
<!-- ```{r volcano} -->
<!-- ``` -->
<!-- ## Модифицированный t-критерий -->
<!-- Модифицированный t-критерий (Witten, Tibshirani, 2007)  -->
<!-- $t_{mod} = \frac {\bar {A} - \bar {B}}{s + s_o}$, -->
<!-- где $s_o$ - это константа, кот. минимизирует коэф. вариации $t_{mod}$. -->
<!-- $s_o$ выбирается при помощи Significance Analysis of Microarrays (SAM) (Tusher et al., 2001) -->
<!-- Модифицированный t-критерий выбирает гены, у которых одновременно большая разница экспрессии и небольшие SE.  -->
</div>
</div>
<div id="moderated-t-test-the-good" class="section level1">
<h1>Moderated t-test (The Good)</h1>
<p><img src="images/the_good1.jpg" width=300px></p>
<p>Реализован в пакете <code>limma</code> <span class="citation">(Ritchie et al. 2015)</span></p>
<p>“Поправленные” стандартные отклонения (shrunk standard deviations)</p>
<p><span class="math display">\[\tilde{s}^{2}_{i} = \frac {s^{2}_{i} d_{i} + s^{2}_{0} d_{0}} {d_{i} + d_{0}}\]</span></p>
<p>Модерированный t-критерий</p>
<p><span class="math display">\[\tilde{t}_{g} = \frac {\bar{M}_{g}} {\tilde{s}_{g}\sqrt{c_{g}}}\]</span></p>
<p>После его применения не будет случаев, когда t-статистика велика просто потому, что стандартная ошибка оказалась маленькой.</p>
<p>Линейные модели (дисперсионный и регрессионный анализ) можно использовать для тестирования сложных гипотез. Модерированный t-критерий, как и обычный, можно использовать для оценки значимости коэффициентов линейных моделей. Мы найдем дифференциально-экспрессируемые белки при помощи линейной модели.</p>
<p>Уравнение линейной регрессии, которое мы будем использовать</p>
<p><span class="math display">\[\hat y _{i} = b _0 + b _1 x _{1i} + \epsilon _{i}\]</span></p>
<p>В нем <span class="math inline">\(\hat y _{i}\)</span> — зависимая переменная, уровень экспрессии, <span class="math inline">\(b _0\)</span> и <span class="math inline">\(b _1\)</span> - коэффициенты, <span class="math inline">\(x _{1i}\)</span> — независимая переменная (предиктор, фактор), описывающая принадлежность гребешка к группе, <span class="math inline">\(\epsilon _{i}\)</span> — остатки от линейной регрессии, <span class="math inline">\(i = 1, 2, \cdots, n\)</span> — значения.</p>
<p>Поскольку мы сравниваем всего два состояния фактора, их можно закодировать при помощи одного единственного предиктора <span class="math inline">\(x _{1i}\)</span>. Этот предиктор будет принимать значение 0 на базовом уровне фактора, и значение 1 на другом уровне. В таком случае, коэффициент <span class="math inline">\(b_0\)</span> будет означать уровень экспрессии на базовом уровне фактора, а коэффициент <span class="math inline">\(b_1\)</span> — разницу уровней экспрессии между двумя уровнями фактора.</p>
<p>Уравнение линейной регрессии можно переписать в виде матриц:</p>
<p><span class="math display">\[\left[\begin{array}{c}
\hat y_1 \\ \hat y_2 \\ \vdots \\ \hat y_n 
\end{array}\right] = 
\left[\begin{array}{cc}
1 &amp; x_{1,1} \\
1 &amp; x_{2,1} \\
\vdots &amp; \vdots \\
1 &amp; x_{n,1} 
\end{array}\right] \cdot
\left[\begin{array}{c}
b _0 \\ b _1
\end{array}\right] +
\left[\begin{array}{c}
\epsilon _1 \\ \epsilon _2 \\ \vdots \\ \epsilon _n
\end{array}\right]
\]</span></p>
<p>Сокращенная форма записи линейной регрессии в матричном виде выглядит так: <span class="math inline">\(\mathbf{\hat y} = \mathbf{X} \mathbf{b} + \mathbf{\epsilon}\)</span>.</p>
<p>Чтобы подобрать в R линейную модель экспрессии при помощи пакета <code>limma</code>, нужно будет создать модельную матрицу <span class="math inline">\(\mathbf{X}\)</span>. Затем при помощи функции <code>lmFit()</code> мы подберем коэффициенты линейной регрессии. Поскольку в этом примере мы сравниваем всего два уровня фактора, чтобы проверить, различается ли экспрессия какого-либо белка между ними, нужно будет всего лишь проверить значимость второго коэффициента линейной модели <span class="math inline">\(b _1\)</span>. Это мы сделаем как раз при помощи модерированного t-критерия. Кроме того, нам придется сделать поправку на множественные сравнения, поскольку мы по-прежнему тестируем много белков сразу. Наконец, мы выберем дифференциально-экспрессируемые белки и построим тепловую карту их экспрессии.</p>
<p><strong>Внимание! В <code>limma</code> сложно учесть технические реплики. Их проще усреднить перед анализом.</strong></p>
<div id="moderated-t-test--r" class="section level2">
<h2>Moderated t-test в R</h2>
<p>В принципе, пакет limma позволяет анализировать данные экспрессии в виде обычных датафреймов, но есть некоторые выгоды при использовании специального формата ExpressionSet.</p>
<p>Загружаем данные, создаем ExpressionSet</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1"><span class="kw">library</span>(Biobase)</a>
<a class="sourceLine" id="cb23-2" data-line-number="2"></a>
<a class="sourceLine" id="cb23-3" data-line-number="3"><span class="co"># Данные экспрессии</span></a>
<a class="sourceLine" id="cb23-4" data-line-number="4">expr_data &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(expr_subset)</a>
<a class="sourceLine" id="cb23-5" data-line-number="5"></a>
<a class="sourceLine" id="cb23-6" data-line-number="6"><span class="co"># Данные о пробах</span></a>
<a class="sourceLine" id="cb23-7" data-line-number="7">pheno_data &lt;-<span class="st"> </span>fact_subset</a>
<a class="sourceLine" id="cb23-8" data-line-number="8">pheno_metadata &lt;-<span class="st"> </span><span class="kw">data.frame</span>(</a>
<a class="sourceLine" id="cb23-9" data-line-number="9">  <span class="dt">labelDescription =</span> <span class="kw">c</span>(<span class="st">&quot;Oxygen concentration&quot;</span>, <span class="st">&quot;Temperature&quot;</span>), </a>
<a class="sourceLine" id="cb23-10" data-line-number="10">  <span class="dt">row.names=</span><span class="kw">c</span>(<span class="st">&quot;Oxygen&quot;</span>, <span class="st">&quot;Temperature&quot;</span>))</a>
<a class="sourceLine" id="cb23-11" data-line-number="11">pheno_data &lt;-<span class="st"> </span><span class="kw">new</span>(<span class="st">&quot;AnnotatedDataFrame&quot;</span>, </a>
<a class="sourceLine" id="cb23-12" data-line-number="12">                 <span class="dt">data =</span> pheno_data, </a>
<a class="sourceLine" id="cb23-13" data-line-number="13">                 <span class="dt">varMetadata =</span> pheno_metadata)</a>
<a class="sourceLine" id="cb23-14" data-line-number="14"></a>
<a class="sourceLine" id="cb23-15" data-line-number="15"><span class="co"># Данные о признаках (белках)</span></a>
<a class="sourceLine" id="cb23-16" data-line-number="16">feature_data &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Spot =</span> <span class="kw">rownames</span>(expr_data))</a>
<a class="sourceLine" id="cb23-17" data-line-number="17"><span class="kw">rownames</span>(feature_data) &lt;-<span class="st"> </span><span class="kw">rownames</span>(expr_data)</a>
<a class="sourceLine" id="cb23-18" data-line-number="18">feature_metadata &lt;-<span class="st"> </span><span class="kw">data.frame</span>(</a>
<a class="sourceLine" id="cb23-19" data-line-number="19">  <span class="dt">labelDescription =</span> <span class="kw">c</span>(<span class="st">&quot;Spot number&quot;</span>),</a>
<a class="sourceLine" id="cb23-20" data-line-number="20">  <span class="dt">row.names =</span> <span class="kw">c</span>(<span class="st">&quot;Spot&quot;</span>))</a>
<a class="sourceLine" id="cb23-21" data-line-number="21">f_data &lt;-<span class="st"> </span><span class="kw">new</span>(<span class="st">&quot;AnnotatedDataFrame&quot;</span>, </a>
<a class="sourceLine" id="cb23-22" data-line-number="22">              <span class="dt">data =</span> feature_data, </a>
<a class="sourceLine" id="cb23-23" data-line-number="23">              <span class="dt">varMetadata =</span> feature_metadata)</a>
<a class="sourceLine" id="cb23-24" data-line-number="24"></a>
<a class="sourceLine" id="cb23-25" data-line-number="25"><span class="co"># Данные об эксперименте</span></a>
<a class="sourceLine" id="cb23-26" data-line-number="26">experiment_data &lt;-</a>
<a class="sourceLine" id="cb23-27" data-line-number="27"><span class="st">  </span><span class="kw">new</span>(<span class="st">&quot;MIAME&quot;</span>,</a>
<a class="sourceLine" id="cb23-28" data-line-number="28">      <span class="dt">name =</span> <span class="st">&quot;Sebastien Artigaud et al.&quot;</span>,</a>
<a class="sourceLine" id="cb23-29" data-line-number="29">      <span class="dt">lab =</span> <span class="st">&quot;lab&quot;</span>,</a>
<a class="sourceLine" id="cb23-30" data-line-number="30">      <span class="dt">contact =</span> <span class="st">&quot;email@domain.com&quot;</span>,</a>
<a class="sourceLine" id="cb23-31" data-line-number="31">      <span class="dt">title =</span> <span class="st">&quot;Proteomic responses to hypoxia at different temperatures in the great scallop (Pecten maximus).&quot;</span>,</a>
<a class="sourceLine" id="cb23-32" data-line-number="32">      <span class="dt">abstract =</span> <span class="st">&quot;Abstract&quot;</span>,</a>
<a class="sourceLine" id="cb23-33" data-line-number="33">      <span class="dt">other =</span> <span class="kw">list</span>(<span class="dt">notes =</span> <span class="st">&quot;partial dataset from Artigaud et al. 2015&quot;</span>))</a>
<a class="sourceLine" id="cb23-34" data-line-number="34"></a>
<a class="sourceLine" id="cb23-35" data-line-number="35"><span class="co"># Собираем вместе</span></a>
<a class="sourceLine" id="cb23-36" data-line-number="36">exp_set &lt;-</a>
<a class="sourceLine" id="cb23-37" data-line-number="37"><span class="st">  </span><span class="kw">ExpressionSet</span>(<span class="dt">assayData =</span> expr_data,</a>
<a class="sourceLine" id="cb23-38" data-line-number="38">                <span class="dt">phenoData =</span> pheno_data,</a>
<a class="sourceLine" id="cb23-39" data-line-number="39">                <span class="dt">featureData =</span> f_data,</a>
<a class="sourceLine" id="cb23-40" data-line-number="40">                <span class="dt">experimentData =</span> experiment_data)</a></code></pre></div>
<p>Мы хотим сравнить уровень экспрессии каждого белка в группах, закодированных фактором <code>Temperature</code>. В наших данных две такие группы по 5 проб.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1"><span class="kw">table</span>(<span class="kw">pData</span>(exp_set)<span class="op">$</span>Temperature)</a></code></pre></div>
<pre class="r-output"><code>## 
## 10C 25C 
##   5   5
</code></pre>
<p>Чтобы подобрать линейную модель в <code>limma</code> нам понадобится модельная матрица.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1"><span class="co"># Модельная матрица</span></a>
<a class="sourceLine" id="cb25-2" data-line-number="2">X &lt;-<span class="st"> </span><span class="kw">model.matrix</span>(<span class="op">~</span><span class="st"> </span>Temperature, <span class="kw">pData</span>(exp_set))</a>
<a class="sourceLine" id="cb25-3" data-line-number="3">X</a></code></pre></div>
<pre class="r-output"><code>##                 (Intercept) Temperature25C
## HT_Br_141_27754           1              0
## HT_Br_142_27755           1              0
## HT_Br_143_27756           1              0
## HT_Br_145_27757           1              0
## HT_Br_153_27758           1              0
## HT_Br_221_30350           1              1
## HT_Br_222_30351           1              1
## HT_Br_227_30353           1              1
## HT_Br_229_30354           1              1
## HT_Br_233_30355           1              1
## attr(,"assign")
## [1] 0 1
## attr(,"contrasts")
## attr(,"contrasts")$Temperature
## [1] "contr.treatment"
</code></pre>
<p>Подбираем линейную модель для <em>i</em>-того белка</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1"><span class="co"># линейная модель</span></a>
<a class="sourceLine" id="cb26-2" data-line-number="2">fit &lt;-<span class="st"> </span><span class="kw">lmFit</span>(exp_set, <span class="dt">design =</span> X, <span class="dt">method =</span> <span class="st">&quot;robust&quot;</span>, <span class="dt">maxit =</span> <span class="dv">1000</span>)</a>
<a class="sourceLine" id="cb26-3" data-line-number="3"><span class="kw">names</span>(fit)</a></code></pre></div>
<pre class="r-output"><code>##  [1] "coefficients"     "stdev.unscaled"   "sigma"           
##  [4] "df.residual"      "cov.coefficients" "pivot"           
##  [7] "rank"             "genes"            "Amean"           
## [10] "method"           "design"
</code></pre>
<p>Теперь самое важное — Empirical Bayes statistics.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" data-line-number="1"><span class="co"># Empirical Bayes statistics</span></a>
<a class="sourceLine" id="cb27-2" data-line-number="2">efit &lt;-<span class="st"> </span><span class="kw">eBayes</span>(fit)</a>
<a class="sourceLine" id="cb27-3" data-line-number="3"><span class="kw">names</span>(efit)</a></code></pre></div>
<pre class="r-output"><code>##  [1] "coefficients"     "stdev.unscaled"   "sigma"           
##  [4] "df.residual"      "cov.coefficients" "pivot"           
##  [7] "rank"             "genes"            "Amean"           
## [10] "method"           "design"           "df.prior"        
## [13] "s2.prior"         "var.prior"        "proportion"      
## [16] "s2.post"          "t"                "df.total"        
## [19] "p.value"          "lods"             "F"               
## [22] "F.p.value"
</code></pre>
<p>Результат — таблица дифференциально-экспрессируемых белков</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" data-line-number="1"><span class="co"># Таблица дифференциально-экспрессируемых белков</span></a>
<a class="sourceLine" id="cb28-2" data-line-number="2"><span class="kw">topTable</span>(efit, <span class="dt">coef =</span> <span class="dv">2</span>)</a></code></pre></div>
<pre class="r-output"><code>##      Spot     logFC  AveExpr         t      P.Value    adj.P.Val        B
## 710   710 -4.206596 19.72662 -16.62161 2.444626e-08 1.092224e-05 9.776019
## 913   913 -3.331280 20.77637 -14.92257 6.574789e-08 1.092224e-05 8.864356
## 268   268 -5.302808 18.48965 -14.95228 6.456348e-08 1.092224e-05 8.853413
## 151   151 -3.656103 18.05204 -14.87908 6.752546e-08 1.092224e-05 8.835799
## 1452 1452  6.367504 13.80349  14.12482 1.085243e-07 1.404304e-05 8.396318
## 75     75 -5.179650 16.63677 -13.44910 1.693901e-07 1.826590e-05 7.994470
## 740   740 -3.951536 18.33269 -13.19759 2.009681e-07 1.830840e-05 7.814747
## 1519 1519  3.176064 18.59995  13.02493 2.263790e-07 1.830840e-05 7.704465
## 1341 1341  3.424297 18.98356  12.61737 3.015737e-07 2.167980e-05 7.433288
## 434   434 -2.957954 18.81784 -12.18224 4.134536e-07 2.675045e-05 7.067613
</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1">numGenes &lt;-<span class="st"> </span><span class="kw">nrow</span>(<span class="kw">exprs</span>(exp_set))</a>
<a class="sourceLine" id="cb29-2" data-line-number="2">full_list &lt;-<span class="st"> </span><span class="kw">topTable</span>(efit, <span class="dt">number =</span> numGenes)</a></code></pre></div>
<pre><code>## Removing intercept from test coefficients</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" data-line-number="1"><span class="co"># View(full_list)</span></a></code></pre></div>
</div>
<div id="ma-plot" class="section level2">
<h2>MA-plot</h2>
<p>Давайте создадим функцию, которая будет рисовать MA-plot, используя объект, возвращенный <code>eBayes()</code>.</p>
<p>Аргументы:</p>
<ul>
<li><code>efit</code> - объект результатов <code>eBayes()</code></li>
<li><code>coef</code> - порядковый номер коэффициента линейной модели, для которого нужно сделать тест</li>
<li><code>n</code> - число белков, которые нужно подписать</li>
<li><code>sigif</code> - выделять ли дифференциальные белки?</li>
<li><code>fdr</code> - уровень FDR коррекции</li>
<li><code>lfc</code> - log fold change</li>
<li><code>text</code> - подписывать ли n белков с сильнее всего различающейся экспрессией<br />
и т.д.</li>
</ul>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" data-line-number="1">MA_limma &lt;-<span class="st"> </span><span class="cf">function</span>(efit, coef, <span class="dt">n =</span> <span class="dv">10</span>, <span class="dt">signif =</span> <span class="ot">TRUE</span>, <span class="dt">fdr =</span> <span class="fl">0.05</span>, <span class="dt">lfc =</span> <span class="dv">0</span>, <span class="dt">text =</span> <span class="ot">TRUE</span>, <span class="dt">cex.text =</span> <span class="fl">0.8</span>, <span class="dt">col.text =</span> <span class="st">&quot;grey20&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;MA-plot&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;Average log-expression&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Expression log-ratio&quot;</span>, <span class="dt">pch =</span> <span class="dv">19</span>, <span class="dt">pch.signif =</span> <span class="dv">21</span>, <span class="dt">col =</span> <span class="st">&quot;darkgreen&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.3</span>, <span class="dt">cex =</span> <span class="fl">0.3</span>, ...){</a>
<a class="sourceLine" id="cb32-2" data-line-number="2">  <span class="co"># соотношение и интенсивность</span></a>
<a class="sourceLine" id="cb32-3" data-line-number="3">  R &lt;-<span class="st"> </span>efit<span class="op">$</span>coefficients[, coef]</a>
<a class="sourceLine" id="cb32-4" data-line-number="4">  I &lt;-<span class="st"> </span>efit<span class="op">$</span>Amean</a>
<a class="sourceLine" id="cb32-5" data-line-number="5">  <span class="co"># прозрачный цвет</span></a>
<a class="sourceLine" id="cb32-6" data-line-number="6">  col_btransp &lt;-<span class="st"> </span><span class="kw">adjustcolor</span>(col, <span class="dt">alpha.f =</span> alpha)</a>
<a class="sourceLine" id="cb32-7" data-line-number="7">  <span class="co"># график</span></a>
<a class="sourceLine" id="cb32-8" data-line-number="8">  <span class="kw">plot</span>(I, R, <span class="dt">cex =</span> cex, <span class="dt">main =</span> main, <span class="dt">pch =</span> pch, <span class="dt">xlab =</span> xlab, <span class="dt">ylab =</span> ylab, <span class="dt">col =</span> col_btransp, ...)</a>
<a class="sourceLine" id="cb32-9" data-line-number="9">  <span class="kw">abline</span>(<span class="dt">h =</span> <span class="dv">0</span>)</a>
<a class="sourceLine" id="cb32-10" data-line-number="10">  <span class="co"># отмечаем дифференциально-экспрессируемые белки</span></a>
<a class="sourceLine" id="cb32-11" data-line-number="11">  <span class="cf">if</span>(signif){</a>
<a class="sourceLine" id="cb32-12" data-line-number="12">    sign &lt;-<span class="st"> </span><span class="kw">p.adjust</span>(efit<span class="op">$</span>p.value[, coef], <span class="dt">method =</span> <span class="st">&quot;BH&quot;</span>) <span class="op">&lt;=</span><span class="st"> </span>fdr</a>
<a class="sourceLine" id="cb32-13" data-line-number="13">    large &lt;-<span class="st"> </span><span class="kw">abs</span>(efit<span class="op">$</span>coefficients[, coef]) <span class="op">&gt;=</span><span class="st"> </span>lfc</a>
<a class="sourceLine" id="cb32-14" data-line-number="14">    <span class="kw">points</span>(I[sign <span class="op">&amp;</span><span class="st"> </span>large], R[sign <span class="op">&amp;</span><span class="st"> </span>large], <span class="dt">cex =</span> cex<span class="op">*</span><span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;orange2&quot;</span>, <span class="dt">pch =</span> pch.signif)</a>
<a class="sourceLine" id="cb32-15" data-line-number="15">  }</a>
<a class="sourceLine" id="cb32-16" data-line-number="16">  <span class="co"># подписываем первые n белков с сильнее всего различающейся экспрессией</span></a>
<a class="sourceLine" id="cb32-17" data-line-number="17">  <span class="cf">if</span>(text){</a>
<a class="sourceLine" id="cb32-18" data-line-number="18">    ord &lt;-<span class="st"> </span><span class="kw">order</span>(efit<span class="op">$</span>lods[, coef], <span class="dt">decreasing =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb32-19" data-line-number="19">    top_n &lt;-<span class="st"> </span>ord[<span class="dv">1</span><span class="op">:</span>n]</a>
<a class="sourceLine" id="cb32-20" data-line-number="20">    <span class="kw">text</span>(I[top_n], R[top_n], <span class="dt">labels =</span> efit<span class="op">$</span>genes[top_n, ], <span class="dt">pos =</span> <span class="dv">4</span>, <span class="dt">cex =</span> cex.text, <span class="dt">col =</span> col.text)</a>
<a class="sourceLine" id="cb32-21" data-line-number="21">  }</a>
<a class="sourceLine" id="cb32-22" data-line-number="22">}</a></code></pre></div>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" data-line-number="1"><span class="kw">MA_limma</span>(efit, <span class="dt">coef =</span> <span class="dv">2</span>, <span class="dt">n =</span> <span class="dv">3</span>)</a></code></pre></div>
<p><img src="04_differential_expression_analysis_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<div id="-5" class="section level3">
<h3>Задание 5</h3>
<p>Сравните графики:</p>
<ul>
<li>MA-plot первых 20 дифференциально экспрессируемых белков</li>
<li>MA-plot первых 20 дифференциально экспрессируемых белков, но таких, чтобы уровень экспрессии различался в 2 раза</li>
<li>MA-plot первых 20 дифференциально экспрессируемых белков с уровнем экспрессии различающимся в 5 раз</li>
</ul>
<button class="btn btn-primary btn-sm" data-toggle="collapse" data-target="#hide_buttonunnamed-chunk-23">
Решение
</button>
<div id="hide_buttonunnamed-chunk-23" class="collapse">
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" data-line-number="1"><span class="kw">MA_limma</span>(efit, <span class="dt">coef =</span> <span class="dv">2</span>, <span class="dt">n =</span> <span class="dv">20</span>, <span class="dt">text =</span> F)</a></code></pre></div>
<p><img src="04_differential_expression_analysis_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" data-line-number="1"><span class="kw">MA_limma</span>(efit, <span class="dt">coef =</span> <span class="dv">2</span>, <span class="dt">n =</span> <span class="dv">20</span>, <span class="dt">text =</span> F, <span class="dt">lfc =</span> <span class="dv">1</span>)</a></code></pre></div>
<p><img src="04_differential_expression_analysis_files/figure-html/unnamed-chunk-23-2.png" width="672" /></p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" data-line-number="1"><span class="kw">MA_limma</span>(efit, <span class="dt">coef =</span> <span class="dv">2</span>, <span class="dt">n =</span> <span class="dv">20</span>, <span class="dt">text =</span> F, <span class="dt">lfc =</span> <span class="kw">log2</span>(<span class="dv">5</span>))</a></code></pre></div>
<img src="04_differential_expression_analysis_files/figure-html/unnamed-chunk-23-3.png" width="672" />
</div>
<p><br /></p>
</div>
</div>
<div id="-----" class="section level2">
<h2>Сохраняем список всех белков в файл</h2>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" data-line-number="1"><span class="kw">dir.create</span>(<span class="st">&quot;results&quot;</span>)</a></code></pre></div>
<pre><code>## Warning in dir.create(&quot;results&quot;): &#39;results&#39; already exists</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" data-line-number="1"><span class="kw">write.table</span>(full_list, <span class="dt">file =</span> <span class="st">&quot;results/pecten_diff_expression.csv&quot;</span>, <span class="dt">sep =</span> <span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>, <span class="dt">quote =</span> <span class="ot">FALSE</span>, <span class="dt">col.names =</span> <span class="ot">NA</span>)</a></code></pre></div>
</div>
<div id="------" class="section level2">
<h2>Добываем дифференциально-экспрессируемые белки для дальнейшей работы</h2>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" data-line-number="1"><span class="co"># Первые 20 дифференциальных белков</span></a>
<a class="sourceLine" id="cb40-2" data-line-number="2">my_list &lt;-<span class="st"> </span><span class="kw">topTable</span>(efit, <span class="dt">coef =</span> <span class="dv">2</span>, <span class="dt">n =</span> <span class="dv">20</span>)</a>
<a class="sourceLine" id="cb40-3" data-line-number="3"><span class="co"># Фильтруем ExpressionSet</span></a>
<a class="sourceLine" id="cb40-4" data-line-number="4">dif_exp_set &lt;-<span class="st"> </span>exp_set[<span class="kw">fData</span>(exp_set)<span class="op">$</span>Spot <span class="op">%in%</span><span class="st"> </span>my_list<span class="op">$</span>Spot, ]</a></code></pre></div>
</div>
<div id="----" class="section level2">
<h2>Тепловая карта экспрессии дифференциальных белков</h2>
<div id="-6" class="section level3">
<h3>Задание 6</h3>
<p>Нарисуйте две тепловые карты диффенциально-экспрессируемых белков:</p>
<ul>
<li>по сырым данным,</li>
<li>после дополнительной стандартизации по белкам.</li>
</ul>
<p>Рассмотрите, чем отличаются эти карты. Какая из них лучше подходит для представления результатов анализа дифференциальной экспрессии?</p>
<button class="btn btn-primary btn-sm" data-toggle="collapse" data-target="#hide_buttonunnamed-chunk-26">
Решение
</button>
<div id="hide_buttonunnamed-chunk-26" class="collapse">
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" data-line-number="1"><span class="kw">library</span>(gplots)</a>
<a class="sourceLine" id="cb41-2" data-line-number="2">dat &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(<span class="kw">exprs</span>(dif_exp_set))</a>
<a class="sourceLine" id="cb41-3" data-line-number="3"></a>
<a class="sourceLine" id="cb41-4" data-line-number="4"><span class="co"># Короткие имена гребешков для графиков</span></a>
<a class="sourceLine" id="cb41-5" data-line-number="5">part1 &lt;-<span class="st"> </span><span class="kw">substr</span>(<span class="dt">x =</span> <span class="kw">pData</span>(dif_exp_set)<span class="op">$</span>Oxygen, <span class="dt">start =</span> <span class="dv">0</span>, <span class="dt">stop =</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb41-6" data-line-number="6">part2 &lt;-<span class="st"> </span><span class="kw">substr</span>(<span class="dt">x =</span> <span class="kw">pData</span>(dif_exp_set)<span class="op">$</span>Temperature, <span class="dt">start =</span> <span class="dv">0</span>, <span class="dt">stop =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb41-7" data-line-number="7"><span class="kw">colnames</span>(dat) &lt;-<span class="st"> </span><span class="kw">make.unique</span>(<span class="kw">paste</span>(part1, part2, <span class="dt">sep =</span> <span class="st">&quot;_&quot;</span>))</a>
<a class="sourceLine" id="cb41-8" data-line-number="8"></a>
<a class="sourceLine" id="cb41-9" data-line-number="9">pal_green &lt;-<span class="st"> </span><span class="kw">colorpanel</span>(<span class="dv">75</span>, <span class="dt">low =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">mid =</span> <span class="st">&quot;darkgreen&quot;</span>, <span class="dt">high =</span> <span class="st">&quot;yellow&quot;</span>)</a>
<a class="sourceLine" id="cb41-10" data-line-number="10"><span class="kw">heatmap.2</span>(dat, <span class="dt">col =</span> pal_green, <span class="dt">scale =</span> <span class="st">&quot;none&quot;</span>, <span class="dt">key=</span><span class="ot">TRUE</span>, <span class="dt">symkey =</span> <span class="ot">FALSE</span>, <span class="dt">density.info =</span> <span class="st">&quot;none&quot;</span>, <span class="dt">trace =</span> <span class="st">&quot;none&quot;</span>, <span class="dt">cexRow =</span> <span class="fl">0.9</span>, <span class="dt">cexCol =</span> <span class="dv">1</span>, <span class="dt">margins =</span> <span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">3</span>), <span class="dt">keysize =</span> <span class="fl">0.8</span>, <span class="dt">key.par =</span> <span class="kw">list</span>(<span class="dt">mar =</span> <span class="kw">c</span>(<span class="dv">3</span>, <span class="fl">0.1</span>, <span class="dv">3</span>, <span class="fl">0.1</span>)))</a></code></pre></div>
<p><img src="04_differential_expression_analysis_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" data-line-number="1">pal_blue_red &lt;-<span class="st"> </span><span class="kw">colorpanel</span>(<span class="dv">75</span>, <span class="dt">low =</span> <span class="st">&quot;steelblue&quot;</span>, <span class="dt">mid =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">high =</span> <span class="st">&quot;red&quot;</span>)</a>
<a class="sourceLine" id="cb42-2" data-line-number="2"><span class="kw">heatmap.2</span>(dat, <span class="dt">col =</span> pal_blue_red, <span class="dt">scale =</span> <span class="st">&quot;row&quot;</span>, <span class="dt">key =</span> <span class="ot">TRUE</span>, <span class="dt">symkey =</span> <span class="ot">FALSE</span>, <span class="dt">density.info =</span> <span class="st">&quot;none&quot;</span>, <span class="dt">trace =</span> <span class="st">&quot;none&quot;</span>, <span class="dt">cexRow =</span> <span class="fl">0.9</span>, <span class="dt">cexCol =</span> <span class="dv">1</span>, <span class="dt">margins =</span> <span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">3</span>), <span class="dt">keysize =</span> <span class="fl">0.8</span>, <span class="dt">key.par =</span> <span class="kw">list</span>(<span class="dt">mar =</span> <span class="kw">c</span>(<span class="dv">3</span>, <span class="fl">0.1</span>, <span class="dv">3</span>, <span class="fl">0.1</span>)))</a></code></pre></div>
<img src="04_differential_expression_analysis_files/figure-html/unnamed-chunk-26-2.png" width="672" />
</div>
<p><br /></p>
<!-- ## `topTreat()` -->
<!-- ```{r} -->
<!-- tfit <- treat(fit, lfc = 1) -->
<!-- topTreat(tfit, coef = 2, number = 20) -->
<!-- ``` -->
<!-- ## Bootstrap -->
<!-- - Нет особенных предположений о форме распределения -->
<!-- - Алгоритм: Считаем t-статистику. Много раз случайным образом переставляем данные между группами и снова считаем t-статистику, чтобы получить ее распределение после случайных перестановок. Считаем уровень значимости t-статистики, как долю пермутаций в которых получилось значение t-статистики больше данного. -->
<!-- - Нужно разумное число повторностей (минимум 4-6), чтобы было что переставлять -->
<!-- ## Дисперсионный анализ (Analysis Of Variance, ANOVA) -->
<!-- - Можно контролировать много факторов сразу -->
<!-- - Нужно неск. повторностей <!-- (я бы сказала, что не меньше 4) -->
<!-- - Должны выполняться условия применимости ANOVA -->
<!-- - Если сравниваемых групп больше двух, то нельзя точно сказать, между  какими группами достоверные различия. После ANOVA нужны пост хок тесты или заранее запланированные сравнения при помощи линейных контрастов.  -->
<!-- ## Адаптивный порог для Fold change -->
<!-- Если при пороге отсечения 2 или 1.5 оказывается выбрано слишком большое число белков, можно применять "адаптивный порог" (Fukuoka et al., 2011). Спорный метод - субъективное число групп с разным пороговым уровнем экспрессии.  -->
<!-- Алгоритм: Нужны две технические повторности, чтобы оценить распределение шума. Нормализуем данные. Логарифмируем. Считаем соотношение экспрессий между техническими повторностями. Делим на $i$-групп по значениям нормализованной экспрессии с численностью $N_i$. (Исключаем группы где оказалось меньше 100 генов/белков - писали для конференции когда-то). Для каждой группы выбрать случайным образом половину генов в группе и найти для них минимальную и максимальную FC (повторить $N_i/2$ раз). Рассчитать доверительный интервал среднего максимального и минимального FC. CIupper * constant - это верхняя граница значимости для группы, а CIlower / constant - это нижняя граница значимости для группы. Если увеличивать constant, то должен снижаться уровень ложноположительных срабатываний. Повторить для других групп. Найденные пороги используются для сравнения тритментов. -->
<!-- Аналогичные методы с разными порогами отсечения: (Tsien et al., 2002b,  Draghici, 2002) -->
<!-- ### Эмпирическая баесовская статистика. -->
<!-- ***** -->
<!-- Применение: смотрим на "типичные" значения стандартных ошибок. Поскольку данные фиксированные и белков много, можно оценить как выглядят "типичные" стандартные ошибки у похожих белков. -->
</div>
</div>
<div class="section level2 unnumbered">
<h2>Ссылки</h2>
<div id="refs" class="references">
<div id="ref-R_Core_Team_2018">
<p>R Core Team. 2018. R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria.</p>
</div>
<div id="ref-Ritchie_2015">
<p>Ritchie, M. E., B. Phipson, D. Wu, Y. Hu, C. W. Law, W. Shi, and G. K. Smyth. 2015. limma powers differential expression analyses for RNA-sequencing and microarray studies. Nucleic Acids Research 43:e47.</p>
</div>
</div>
</div>
</div>

<p><small>
(C) 2019 Marina Varfolomeeva, Arina Maltseva
</small></p>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
