---
title: "Анализ протеомных данных с использованием R"
subtitle: "Материалы к курсу Протеомика. Возможности, методы, анализ данных"
html_document:
  self_contained: false
  css: style.css
  highlight: haddock
  theme: flatly
  mathjax: null
  toc: no
  toc_depth: 2
  toc_float:
    collapsed: false
  lib_dir: libs
  includes:
    in_header: include/in_header.html
    after_body: include/after_body.html
bibliography: 
  - "bibs/references.bib"
  - "bibs/01_packages.bib"
  - "bibs/02_packages.bib"
  - "bibs/03_packages.bib"
  - "bibs/04_packages.bib"
  - "bibs/05_packages.bib"
  - "bibs/06_packages.bib"
csl: "bibs/ecology.csl"
---

<style type="text/css">
.title {
  display: visible;
}
</style>

<div class="row">
<div class="col-sm-10">

## Расписание и контакты

- Варфоломеева Марина Александровна -  marina.nikolaeva[]gmail.com
- Мальцева Арина Леонидовна - 


## До начала курса

Установите пожалуйста [R](http://cran.r-project.org/) и [RStudio](https://www.rstudio.com/products/rstudio/download/preview/).
Запустите RStudio (с правами администратора, если вы в Windows) и, для начала, установите несколько пакетов. Для этого в консоли RStudio выполните следующие команды:

```
install.packages(c("ggplot2", "gplots", "fpc", "pvclust", "Hmisc"))

source("https://bioconductor.org/biocLite.R")
biocLite(c("Biobase", "prot2D", "impute", "pcaMethods", "limma"))
```
Прочие пакеты для R будем устанавливать по мере необходимости.

Если что-то не получается --- пишите.

## Ссылки и ресурсы

- [Исходный код в RMarkdown](http://github.com/varmara/proteomics-course)
- [Другие ресурсы и книги для изучения R и статистики](pages/resources.html)
- [Правила хорошего кода](coding_practices.html)

---

## Темы

[О модуле Анализ протеомных данных](00_introduction.html)

1.Знакомство с R. [Заметки](01_introduction_to_r.html)

2.Предварительная обработка данных. [Заметки]<!--- (02_data_preprocessing.html) --->

3.Классификация. [Заметки]<!--- (03_classification.html) --->

4.Выявление дифференциально-экспрессируемых пептидов. [Заметки]<!--- (04_differential_expression_analysis.html) --->

5.Многомерные методы (PCA). [Заметки]<!--- (05_multivariate_methods_pca.html) --->

<!-- 6.Многомерные методы (PLS-DA). [Заметки](06_multivariate_methods_pls-da.html) --->



</div>
</div>

