---
title: "Протокол анализа данных"
output:
  html_document:
    toc: no
---

1. Правильно ли открылись данные? Правильно ли определены типы переменных?
1. Сколько пептидов и сколько проб в файле с экспрессией? Для всех ли проб указаны значения факторов в файле с факторами? (т.е. соответствует ли число строк в файле с факторами числу столбцов в файле с экспрессией?)
1. Сколько групп закодировано в каждом факторе? Сколько проб входит в каждую из групп?
1. Сколько пропущенных значений экспрессии для каждого из пептидов? Если есть пропуски --- проводим импутацию.
1. Нужна ли нормализация? RI-plot или боксплот. Если нужно --- нормализуем.
1. Лог-трансформируем данные.
1. (Не обязательно, но возможно) Разведочный кластерный анализ, чтобы выяснить нет ли таких отдельных пептидов или проб, которые сильно отличаются от других. Можно выявить технические ошибки.
1. Усредняем технические повторности. (К сожалению, не могу предложить вам универсального способа сделать это в R, кроме как напрямую усреднить соответствующие столбцы)
1. Строим дендрограмму проб. Получаем значения поддержки ветвей (и/или считаем другие индексы оценки качества кластеризации).
1. Проводим анализ дифференциальной экспрессии. Полную таблицу дифференциально-экспрессируемых пептидов можно включить в приложения. Краткую таблицу и/или тепловую карту экспрессии всех дифференциальных пептидов  можно включить в текст.

В итоге у вас должны получится:

- Дендрограмма проб.
- Таблица дифференциально-экспрессируемых пептидов (краткая или полная).
- Тепловая карта экспрессии дифференциальных пептидов.
